//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMSoftware.AsciiGeneratorDotNet {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MMMMMMM@@@@@@@WWWWWWWWWBBBBBBBB000000008888888ZZZZZZZZZaZaaaaaa2222222SSSSSSSXXXXXXXXXXX7777777rrrrrrr;;;;;;;;iiiiiiiii:::::::,:,,,,,,.........       </string>
  <string>@@@@@@@######MMMBBHHHAAAA&amp;&amp;GGhh9933XXX222255SSSiiiissssrrrrrrr;;;;;;;;:::::::,,,,,,,........        "", ""#WMBRXVYIti+=;:,. "", ""##XXxxx+++===---;;,,...    </string>
  <string>@%#*+=-:. </string>
  <string>#¥¥®®ØØ$$ø0oo°++=-,.    </string>
  <string># </string>
  <string>01 </string>
  <string>█▓▒░ </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultRamps {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultRamps"]));
            }
            set {
                this["DefaultRamps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string> #,.0123456789:;@ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz$</string>
  <string> ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz</string>
  <string> 1234567890</string>
  <string>M@WB08Za2SX7r;i:;. </string>
  <string>@#MBHAGh93X25Sisr;:, </string>
  <string>█▓▒░ </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultValidCharacters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultValidCharacters"]));
            }
            set {
                this["DefaultValidCharacters"] = value;
            }
        }
    }
}
